"""Initial schema

Revision ID: cf4dfeadc4f0
Revises: 
Create Date: 2026-04-13 15:09:12.493542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf4dfeadc4f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.String(length=10), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.String(length=50), nullable=True),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('hospital',
    sa.Column('hospital_id', sa.String(length=10), nullable=False),
    sa.Column('hospital_name', sa.String(length=100), nullable=False),
    sa.Column('hospital_location', sa.String(length=150), nullable=True),
    sa.Column('hospital_type', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_table('ml_model',
    sa.Column('model_id', sa.String(length=10), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('algorithm_type', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('super_admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('doctor',
    sa.Column('doctor_id', sa.String(length=10), nullable=False),
    sa.Column('hospital_id', sa.String(length=10), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.CheckConstraint('experience_years >= 0', name='chk_doctor_experience'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('medicine',
    sa.Column('medicine_id', sa.String(length=10), nullable=False),
    sa.Column('hospital_id', sa.String(length=10), nullable=False),
    sa.Column('medicine_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medicine_id')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.String(length=10), nullable=False),
    sa.Column('hospital_id', sa.String(length=10), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('registration_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('training_round',
    sa.Column('round_id', sa.String(length=10), nullable=False),
    sa.Column('model_id', sa.String(length=10), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('global_model_accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('actual_participants', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_model.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('round_id')
    )
    op.create_table('contribution_score',
    sa.Column('contribution_id', sa.String(length=10), nullable=False),
    sa.Column('hospital_id', sa.String(length=10), nullable=False),
    sa.Column('round_id', sa.String(length=10), nullable=False),
    sa.Column('contribution_value', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('reputation_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['training_round.round_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('medical_record',
    sa.Column('record_id', sa.String(length=10), nullable=False),
    sa.Column('patient_id', sa.String(length=10), nullable=False),
    sa.Column('doctor_id', sa.String(length=10), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('model_update',
    sa.Column('update_id', sa.String(length=10), nullable=False),
    sa.Column('round_id', sa.String(length=10), nullable=False),
    sa.Column('hospital_id', sa.String(length=10), nullable=False),
    sa.Column('model_hash', sa.String(length=255), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('loss_value', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('submission_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['training_round.round_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_table('blockchain_verification',
    sa.Column('verification_id', sa.String(length=10), nullable=False),
    sa.Column('update_id', sa.String(length=10), nullable=False),
    sa.Column('blockchain_transaction_hash', sa.String(length=255), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['update_id'], ['model_update.update_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verification_id'),
    sa.UniqueConstraint('update_id')
    )
    op.create_table('lab_test',
    sa.Column('test_id', sa.String(length=10), nullable=False),
    sa.Column('record_id', sa.String(length=10), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=True),
    sa.Column('test_result', sa.Text(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_record.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('prescription',
    sa.Column('prescription_id', sa.String(length=10), nullable=False),
    sa.Column('record_id', sa.String(length=10), nullable=False),
    sa.Column('medication_name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.CheckConstraint('duration_days > 0', name='chk_prescription_duration'),
    sa.ForeignKeyConstraint(['record_id'], ['medical_record.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription')
    op.drop_table('lab_test')
    op.drop_table('blockchain_verification')
    op.drop_table('model_update')
    op.drop_table('medical_record')
    op.drop_table('contribution_score')
    op.drop_table('training_round')
    op.drop_table('patient')
    op.drop_table('medicine')
    op.drop_table('doctor')
    op.drop_table('super_admin')
    op.drop_table('ml_model')
    op.drop_table('hospital')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
